### ISSUE TITLE
main story I

### ISSUE THREAD

**Issue by KawinChoosin** [KawinChoosin/Project-Visual-Novel#1]
ขอstoryคร่าวๆที่คิดไว้เเล้วหน่อย

**Comment by kaewtar** [comment]
https://www.notion.so/Story-Project-e2f103ba19b545f9ae95301c8cc9687a?pvs=4

**Comment by kaewtar** [comment]
โครงเรื่องนะ

**Comment by kaewtar** [comment]
Ver.1
https://www.notion.so/Story-Project-e2f103ba19b545f9ae95301c8cc9687a?pvs=4

**Comment by kaewtar** [comment]
Sources 
https://docs.google.com/document/d/1NHbZWQ61yLCD_lO8aDHgrUMUwioBRbnGSxtx_blUZXc/edit?usp=sharing

**Comment by kaewtar** [comment]
Open
https://docs.google.com/document/d/1gNen7iF0IHozBmTGf3wDly5AlKdmD8Dvj1sHBV68RM8/edit?usp=sharing

**Comment by kaewtar** [comment]
[project mind map.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10777309/project.mind.map.pdf)

**Comment by kaewtar** [comment]
Draft - game
https://docs.google.com/document/d/1lk2w8ds6hpJ9XjgiuNd782oxlmSALqz8A9iFYqCM4lw/edit?usp=sharing

**Comment by kaewtar** [comment]
[pj++.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10783445/pj%2B%2B.pdf)
อัพเดท

**Comment by kaewtar** [comment]
draft games 
https://docs.google.com/document/d/1lk2w8ds6hpJ9XjgiuNd782oxlmSALqz8A9iFYqCM4lw/edit?usp=sharing

**Comment by kaewtar** [comment]
Update.2
[update 2.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10807818/update.2.pdf)

**Comment by kaewtar** [comment]
For design
https://www.canva.com/design/DAFbCVUv-Cs/AayYN2_2vDl3-ZC9Hh6xZw/edit?utm_content=DAFbCVUv-Cs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by kaewtar** [comment]
Eng ver.
https://docs.google.com/document/d/1HG5iwCd8ftz4a2dUWxEQz7btvoqOIXpdpimPpxwrg2A/edit?usp=sharing

**Comment by kaewtar** [comment]
Thai ver.
https://docs.google.com/document/d/13Hp7I8r_tEhcZbz_W83owyqx3p4qZ8kocQKoQ3Vgzvk/edit?usp=sharing

**Comment by kaewtar** [comment]
update+
[update 4.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10842797/update.4.pdf)

**Comment by KawinChoosin** [comment]
เดี๋ยวขอสรุปเนื้อเรื่องใหม่เเบบmind mapเหมือนไฟล์ล่าสุดหน่อยนะ เราว่าจะcopyไฟล์เเก้วตามาเเก้ทับที่เป็นภาษาอังกฤษ มันน่าจะดูง่ายกว่าเเละตอนเอาไปใช้น่าจะสะดวกกว่า

**Comment by kaewtar** [comment]
update ++
[update 5.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10886718/update.5.pdf)

**Comment by kaewtar** [comment]
### _**complete story for coding**_
https://docs.google.com/document/d/14VQrAHLf_5vrNeKe6jL0UzK_rIfgK5RwMzpUicGvJGw/edit?usp=sharing

**Comment by kaewtar** [comment]
Update complete files
[Story of game - final.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10889696/Story.of.game.-.final.pdf)

**Comment by kaewtar** [comment]
### **Update complete file**
[Story of game - final.pdf](https://github.com/KawinChoosin/Project-Visual-Novel/files/10889706/Story.of.game.-.final.pdf)

**Comment by kaewtar** [comment]
ตอนนี้สตอรี่เสร็จหมดทุกส่วนแล้วนะะะ
หลักๆจะมีที่เป็นบททดสอบ อยู่ 3 อัน คือ เกม24 (ความฉลาด) , ไฮโล (ความตระหนัก) อีกอันตัดไปละ  ,แล้วก็ที่สู้กับมังกรตอนจบ

**Comment by kaewtar** [comment]
ตอนนี้สตอรี่เสร็จหมดทุกส่วนแล้วนะะะ
หลักๆจะมีที่เป็นบททดสอบ อยู่ 3 อัน คือ เกม24 (ความฉลาด) , ไฮโล (ความตระหนัก)  ,แล้วก็ที่สู้กับมังกรตอนจบ
